// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicProgressLogAPI.Data;

#nullable disable

namespace MusicProgressLogAPI.Migrations
{
    [DbContext(typeof(MusicProgressLogDbContext))]
    [Migration("20231228014102_UserRelationship-Pieces and UserRelationship-ProgressLogs foreign key constraints")]
    partial class UserRelationshipPiecesandUserRelationshipProgressLogsforeignkeyconstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicProgressLogAPI.Models.Domain.AudioFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MIMEType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AudioFiles");
                });

            modelBuilder.Entity("MusicProgressLogAPI.Models.Domain.Piece", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Composer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserRelationshipId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserRelationshipId");

                    b.ToTable("Pieces");
                });

            modelBuilder.Entity("MusicProgressLogAPI.Models.Domain.ProgressLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AudioFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PieceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserRelationshipId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AudioFileId");

                    b.HasIndex("PieceId");

                    b.HasIndex("UserRelationshipId");

                    b.ToTable("ProgressLogs");
                });

            modelBuilder.Entity("MusicProgressLogAPI.Models.Domain.UserRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRelationships");
                });

            modelBuilder.Entity("MusicProgressLogAPI.Models.Domain.Piece", b =>
                {
                    b.HasOne("MusicProgressLogAPI.Models.Domain.UserRelationship", "UserRelationship")
                        .WithMany("Pieces")
                        .HasForeignKey("UserRelationshipId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserRelationship");
                });

            modelBuilder.Entity("MusicProgressLogAPI.Models.Domain.ProgressLog", b =>
                {
                    b.HasOne("MusicProgressLogAPI.Models.Domain.AudioFile", "AudioFile")
                        .WithMany()
                        .HasForeignKey("AudioFileId");

                    b.HasOne("MusicProgressLogAPI.Models.Domain.Piece", "Piece")
                        .WithMany()
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicProgressLogAPI.Models.Domain.UserRelationship", "UserRelationship")
                        .WithMany("ProgressLogs")
                        .HasForeignKey("UserRelationshipId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AudioFile");

                    b.Navigation("Piece");

                    b.Navigation("UserRelationship");
                });

            modelBuilder.Entity("MusicProgressLogAPI.Models.Domain.UserRelationship", b =>
                {
                    b.Navigation("Pieces");

                    b.Navigation("ProgressLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
